# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=800']
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.49.14
    hooks:
      - id: swiftformat
#  - repo: https://github.com/realm/SwiftLint
#    rev: 0.48.0
#    hooks:
#      - id: swiftlint
